# This is a basic workflow that is Auto triggered
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
name: CI Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
